name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./front/pom.xml
          mvn clean package -f ./store/pom.xml
          mvn clean package -f ./rider/pom.xml
          mvn clean package -f ./customer/pom.xml

      - name: Docker Build and push for Front
        uses: docker/build-push-action@v4
        with:
          context: ./front
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/front:latest
            ghcr.io/${{ github.repository }}/front:${{ github.ref_name }}
            
      - name: Docker Build and push for Store
        uses: docker/build-push-action@v4
        with:
          context: ./store
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/store:latest
            ghcr.io/${{ github.repository }}/store:${{ github.ref_name }}
            
      - name: Docker Build and push for Rider
        uses: docker/build-push-action@v4
        with:
          context: ./rider
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/rider:latest
            ghcr.io/${{ github.repository }}/rider:${{ github.ref_name }}
            
      - name: Docker Build and push for Customer
        uses: docker/build-push-action@v4
        with:
          context: ./customer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customer:latest
            ghcr.io/${{ github.repository }}/customer:${{ github.ref_name }}
            
